name: 'Site Settings'
type: module
description: 'Module containing various site settings and blocks.'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'GovCore'
configure: system.site_information_settings
dependencies:
  - drupal:image
