core.entity_view_mode.*.*.third_party.govcore_core:
  type: mapping
  label: 'GovCore'
  mapping:
    description:
      type: string
      label: 'Description'
    internal:
      type: boolean
      label: 'Internal'

core.entity_form_mode.*.*.third_party.govcore_core:
  type: mapping
  label: 'GovCore'
  mapping:
    description:
      type: string
      label: 'Description'
    revision_ui:
      type: boolean
      label: 'Show the revision UI on entity forms using this mode'

user.role.*.third_party.govcore_core:
  type: mapping
  label: 'GovCore'
  mapping:
    description:
      type: string
      label: 'Description'

govcore_core.versions:
  type: sequence
  label: 'Extension versions'
  sequence:
    type: string
    label: 'Semantic version number'
